- Makefile
This allows people to run
bmake publish VERSION=x.y
on Ubuntu.
> replace "make" with "${MAKE}"

- proto/proto_conn.c
The wording in the comment now matches the wording of the comment
of dispatch_accept.
> Fix typo in comment of proto_conn_create

- README.md
The github "releases" are merely snapshots of the git repository, which uses
BSD Makefiles.
This adds emoji to the README.md, because spiped is a serious project and serious projects need emoji.  (they make sense, I swear!)
This addresses the root cause of #26
> README.md: add warning to download from tarsnap.com

- libcperciva/POSIX/posix-cflags.sh
- libcperciva/POSIX/posix-l.sh
This was a fun one!  TL;DR: my OS doesn't update the ownership of /dev/stderr
when su'ing into a new account, so attempting to redirect to /dev/stderr fails
with a "permission denied".
My main user (the one running X11) is gperciva.  I opened an xterm, did
$ su td
(for "tarsnap development"), and then
td@gin: ~/src/spiped/libcperciva/POSIX (stderr-compatibility)
$ ls -lL /dev/stderr
crw--w---- 1 gperciva tty 136, 2 Dec 20 11:43 /dev/stderr
According to at least one comment on an internet forum (what could go
wrong?!), the shell is *supposed* to treat /dev/stderr as a special case (and
internally use 1>&2), but if that file exists, then it attempts to write
directly to it.  Which fails, since ownership of /dev/stderr is not updated
when using su.
Long description here: …
> Compatibility with /dev/stderr and su and linux

- spiped/dispatch.c
- spiped/dispatch.h
- spiped/main.c
- spiped/spiped.1
I put the man-page documenting of `-1` in a separate commit since you might tell me it should be undocumented.  My vote (which has no value) is that we should still document it, because I won't be able to remember it otherwise, and it's not like anybody can do anything nasty if they know about `-1`.  (and even if they could, they could discover it from the source code anyway).
Since `spipe` can quit with `^D`, I didn't add `-1` there, but you might want me to do so anyway for consistency.
> Run spiped only once with -1

- Makefile
Without this, we were recompiling the binaries every time we ran "make"
because cpusupport-config.h was being regenerated, and cpusupport-config.h is
now listed as an explicit dependency for cpusupport_x86_aesni.o.
> build: add target for cpusupport-config.h

- spiped/main.c
events_timer_cancel(graceful_shutdown_timer_cookie);
must happen before
dispatch_shutdown(dispatch_cookie);
because otherwise the timer could trigger after the shutdown (which would try
to use dispatch_cookie after it was freed).
> spiped: track & clean up graceful shutdown cookie

- .travis.yml
We still need the explicit CFLAGS and LDFLAGS, but we don't need to
brew install openssl.
> travis-CI: osx image already includes openssl

- Makefile.BSD
The earlier line worked by coincidence: when there was no NOINST, it would display the error:
/bin/sh: 1: [: -eq: unexpected operator
and then take the "else" command.  The end result was the Makefiles that we desired, but we didn't receive the result in an appealing manner.
> build: fix "if ... NOINST" line

- libcperciva/cpusupport/cpusupport_x86_aesni.c
This macro is only used in code that hidden by the same #ifdef.
> libcperciva: put CPU macros inside relevant #ifdef

- tests/01-connection-open-close-single.sh
- tests/02-connection-open-timeout-single.sh
- tests/nc-client/main.c
Yes, given the specific values inside this file's send_input() function,
we're not expecting to see a lenwrit which is neither -1 nor send->nchars.
However, I think the code is more clear this way, and it's not unlikely that
I'll end up copying bits of this file the next time I want to send data over a
network.  Also, if we did somehow see an unexpected value for lenwrit, I think
it would be nice to have a specific error message for that case.
> tests/nc-client: clarify client network errors, block on socket close

- libcperciva/events/events_network.c
On MacOS X, nfds_t is (unsigned int) rather than (unsigned long).
This cast is safe because the only place in which we increase nfds is in
growpollfd(), and we do so in response to adding a new (int)fd to the pollfd
array, and thus therefore nfds won't exceed INT_MAX.
> libcperciva poll: explicit cast to (nfds_t)nfds

- libcperciva/util/getopt.h
Previously, scan-build in clang would produce warnings in the form:
```
main.c:159:17: warning: Null pointer passed as an argument to a 'nonnull' parameter
if ((opt_p = strdup(optarg)) == NULL)
```
This is not a particularly deterministic bug; creating the obvious minimal
example fails to reproduce this warning.  It seems to require some additional
code to trigger this warning, and a minimal reproduction in one version of
clang can fail to show this problem in a later version of clang.
> libcperciva getopt: silence scan-build warnings

- spipe/main.c
- spiped/main.c
This does not alter the -n option, as that will happen in a separate PR
(wherein -n 0 will gain semantic meaning).
> Don't allow multiple -o or -r options

- tests/06-send-data-system-spiped.sh
The "shared" function will print a "SKIP" at the end of the line, so no need
to print it in the middle as well.
> tests: improve message if no system spiped exists

- tests/Makefile.inc
The test code doesn't have man pages; on recent FreeBSD setting MAN=
is necessary in order to avoid having MAN1 autofilled.
> Set MAN= in tests/Makefile.inc

- .gitignore
The valgrind tests aren't ready (and thus aren't in git master), so I haven't
added tests-valgrind/ to gitignore.
> gitignore: tests-output/

- tests/shared_test_functions.sh
Using "-opid,cmd" worked on Debian/Ubuntu, but complains on Alpine busybox.  In
addition, it acts (almost*) the same as "-opid" on FreeBSD and OpenBSD.
* it does complain "ps: cmd: keyword not found", but this message occurs
at the beginning of the listing, so it's not visible on the screen when testing
with "ps -Aopid,cmd".
> tests: use POSIX arguments with ps(1)

- Makefile
POSIX says that command expansion (e.g., via backticks) takes place
before field splitting; as such,
export FOO=`echo foo bar`
should have the same effect as
export FOO=foo bar
i.e., to set FOO=foo and then add the variables FOO and bar (which
will be set to "" if not otherwise initialized) to the environment.
Oddly enough, both bash and FreeBSD's sh get this wrong, and act as
if there are quotes around "FOO=`echo foo bar`".
In the case where the posix-l.sh or posix-cflags.sh shell scripts
emitted multiple options, this resulted in the intended behaviour
being accidentally provided by bash and FreeBSD's sh, while the code
breaks (as it should) in dash (which is POSIX-compliant here).
This commit adds the missing quotes, to ensure that POSIX-compliant
shells give us the intended behaviour.
> Properly quote shell strings

- spiped/dispatch.c
- spiped/main.c
spiped will segfault on shutdown if target address re-resolution is in
use. This is due to two cases of accessing memory that will be freed by
other parts of the code on the first re-resolution cycle. To avoid this:
The DNS timer has to be marked as expired so it's not freed on shutdown
if already expired. Incidentally, the new instance's is recorded so it
can be cancelled on shutdown if not already expired.
Also, the initial target address list as taken from the command line has
to be marked as under dispatch's purview after dispatch_accept() has
been called.
> Avoid SIGSEGV on shutdown with target re-resolution

- spipe/main.c
- spiped/main.c
- tests/dnsthread-resolve/main.c
- tests/nc-client/main.c
- tests/nc-server/simple_server.c
Events clean-up is done via atexit and the function was deprecated in
b164ec07fb7015de5c33cfa2c4bd9e835a88c5f2.
> Don't use events_shutdown()

- .github/workflows/compile.yml
GitHub is depreciating macos 10.15.
> Actions: move from macOS 10.15 to 11

- libcperciva/util/sock.c
- libcperciva/util/sock_util.c
- libcperciva/util/sock_util.h
- spipe/main.c
- spiped/main.c
A source or destination address of the form ":1234" is parsed as a hostname of "" which is guaranteed to never work.  While we don't want to give special error messages for all possible invalid addresses, this particular case can easily be produced from a broken shell script (with a hostname variable accidentally not set), so it's worth having a special error message.
Suggested by:	Ross Richardson
> Give an error for addresses lacking a hostname
